services:
  admin-app:
    build:
      context: ./anybotics-admin
    ports:
      - "4000:3000"
    # depends_on:
    #   - auth-service

  users-app:
    build:
      context: ./anybotics-workforce-ng
    ports:
      - "4001:4200"

  # auth-service:
  #   build:
  #     context: ./anybotics.auth
  #   ports:
  #     - "3001:8080"
  #     - "3002:8081"
    
  # TODO: add more services here
